# @package _global_

defaults:
  - override /data: birddatafull
  - override /model: timm_classifier
  - override /callbacks: default
  - override /trainer: gpu
  - override /logger: default

# Experiment name
name: bird_200_vit_tiny

seed: 42

data:
  batch_size: 16
  num_workers: 4
  pin_memory: true

trainer:
  min_epochs: 20
  max_epochs: 50
  gradient_clip_val: 0.5
  precision: 16
  accelerator: 'gpu'
  devices: 1
  accumulate_grad_batches: 4

model:
  _target_: src.model_builder.timm_classifier.TimmClassifier
  base_model: vit_tiny_patch16_224
  num_classes: 200
  pretrained: true
  learning_rate: 1e-4
  weight_decay: 5e-5
  patience: 15
  factor: 0.1
  min_lr: 1e-7
  dropout_rate: 0.25

callbacks:
  early_stopping:
    patience: 20
    monitor: "val/acc"
    mode: "max"
    min_delta: 0.0005
  model_checkpoint:
    dirpath: ${oc.env:PROJECT_ROOT}/checkpoints/${name}/
    filename: "best_model"
    monitor: "val/acc"
    mode: "max"
    save_top_k: 3
    save_last: True

tags: ["bird_200", "classification", "vit_tiny"]

s3_model_save_location: "pytorch-model-emlov4"
ckpt_path: ${oc.env:PROJECT_ROOT}/checkpoints/${name}/best_model.ckpt
