# @package _global_

defaults:
  - override /data: food100data
  - override /model: timm_classifier
  - override /callbacks: default
  - override /trainer: gpu
  - override /logger: default

# Experiment name
name: food_101_vit_tiny

seed: 42

data:
  batch_size: 32
  num_workers: 4
  pin_memory: true

# Increase the number of epochs for better training
trainer:
  min_epochs: 1
  max_epochs: 65
  gradient_clip_val: 0.5
  precision: 16
  accelerator: 'gpu'
  devices: 1
  accumulate_grad_batches: 8

# Adjust learning rate and batch size
model:
  _target_: src.model_builder.timm_classifier.TimmClassifier
  base_model: vit_tiny_patch16_224
  num_classes: 101
  pretrained: true
  learning_rate: 3e-4
  weight_decay: 2e-4
  patience: 3
  factor: 0.6
  min_lr: 1e-6
  dropout_rate: 0.15

# Early stopping configuration
callbacks:
  early_stopping:
    patience: 10
    monitor: "val/acc"
    mode: "max"
    min_delta: 0.001
  model_checkpoint:
    dirpath: ${oc.env:PROJECT_ROOT}/checkpoints/${name}/
    filename: "best_model"
    monitor: "val/acc"
    mode: "max"
    save_top_k: 1
    save_last: True

# Tags for experiment tracking
tags: ["food_101", "classification", "vit_tiny"]

s3_model_save_location: "pytorch-model-emlov4"
ckpt_path: ${oc.env:PROJECT_ROOT}/checkpoints/${name}/best_model.ckpt
